[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  
[[plugins]]
  package = "netlify-plugin-cache-folder"
