[build]
  command = "npm run generate"
  publish = "dist"
  
[context.production]
  environment = { NPM_FLAGS = "--no-optional", CI = "1" }

  
[[plugins]]
  package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
      branches = ['main']

[[plugins]]
  package = "@netlify/plugin-functions-install-core"