[[redirects]]
  from = "https://bbb.dev/*"
  to = "/.netlify/functions/smolify?path=:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/posts/*"
  to = "/blog/:splat"
  status = 301
  force = true