name: Continuous Deployment
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
jobs:
  deploy:
    name: Build & deploy site to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - run: "flyctl deploy  --build-arg ARG_TWITCH_CLIENT_ID=${{secrets.TWITCH_CLIENT_ID}} --build-arg ARG_TWITCH_CLIENT_SECRET=${{secrets.TWITCH_CLIENT_SECRET}} --build-arg ARG_CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}} --build-arg ARG_CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}} --build-arg ARG_CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}} --build-arg ARG_TWITCH_CHANNEL_ID=${{secrets.TWITCH_CHANNEL_ID}}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
