name: Continuous Deployment
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
env:
  TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
  TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}
  TWITCH_CHANNEL_ID: ${{secrets.TWITCH_CHANNEL_ID}}
jobs:
  deploy:
    name: Build & deploy site to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies & prep data
        run: |
          npm install
          node ./readme/index.js

      - name: Build site
        run: |
          npm run build
