name: Update Notion Contacts
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
env:
  GH_PAT: ${{secrets.GH_PAT}}
  TWITTER_BEARER_TOKEN: ${{secrets.TWITTER_BEARER_TOKEN}}
  NOTION_CONTACT_DATABASE_ID: ${{secrets.NOTION_CONTACT_DATABASE_ID}}
  NOTION_OAUTH_TOKEN: ${{secrets.NOTION_OAUTH_TOKEN}}
jobs:
  update_profile_data:
    name: Update Notion Contacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Notion Contacts
        run: |
          cd notion-contacts
          npm install
          node index.js
