name: Update profile
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update_profile_data:
    name: Update profile data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          cd scripts/readme
          npm install
          node index.js
      - name: Commit changes
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull origin main
          git add .
          git commit -m "Updating README"
          git push origin main